### PR TITLE
Implement basic authentication/login

### PR DESCRIPTION
**Pull request by daosgava**
Description:
- Polish the MVC model
- Add a layout and navbar components for consistency
- Add an authentication controller and routes
- Create login and registration forms
- Add middleware to protect routes
- Rename the post page to Dashboard

TODO:
- Handling form errors for login and registration

Relates to Trello Card:

https://trello.com/c/cxv7xdyS/14-implement-basic-authentication-login

Images:

Screenshot 2024-12-13 at 2 16 45 PM
Screenshot 2024-12-13 at 2 16 51 PM
Screenshot 2024-12-13 at 2 17 03 PM
Screenshot 2024-12-13 at 5 24 03 PM

### CODE REVIEW

**Comment by daosgava** [comment]
@marlon-deakin I made some progress on the registration part, as I needed it to test the login flow. We still need to work on form validation and error handling for both login and registration. If you want, you can work on that in another branch as part of your card. Let me know what you think.

**Review by ashleywd — CHANGES_REQUESTED** [review]
All good with me. Just need to incorporate our post creation functionality.

We had the post there as part of a modal, feel free to change this as well if you think you can do it better. Also feel free to link userID from the post to the user profile and remove the userID as a string from the post creation.

**Review by ashleywd — APPROVED** [review]
This all looks good @daosgava. FYI, I went ahead and implemented the error handling on login and registration posts. Also deleted the manual userID from the form and linked the form submission to the userID stored in the session.

If you're happy you can go ahead and merge the changes to main.

**Comment by daosgava** [comment]
Thanks, @ashleywd! It looks great :). I just ran Prettier in VS Code to fix the indentation.

**Pull request merged**
